### ISSUE TITLE
Fix paths in reproducing figures

### ISSUE THREAD

**Issue by ShravanTata** [NeLy-EPFL/NeuroMechFly#38]
Under the miscellaneous section, I found it difficult and time consuming to get the path to the necessary data in the local github repo (e.g. joint angles) for reproducing Figures 5, 6, and 7. Instead of declaring the path as “path/to/angles”, the authors should state the path in the local github repo (e.g. “~/NeuroMechFly/scripts/neuromuscular_optimization/simulation_last_run/gen_final/sol_fastest”). This will make reproducing the figures easier.

**Comment by gizemozd** [comment]
Paths have been changed to an explicit version. However, users still need to check NeuroMechFly's directory and add the name of the simulation results dump folder.
