### ISSUE TITLE
cannot open blender file 

### ISSUE THREAD

**Issue by zhaojiachen1994** [NeLy-EPFL/NeuroMechFly#45]
Hello, NeuroMechFly is an excellent work. 
But, We found the blender file in "./data/design/blender/neuromechfly_full_model.blend" is only 138B, we cann't open it

**Comment by gizemozd** [comment]
Hello, thank you very much for appreciating our work. 

The blender file is stored via git lfs. To download it, you should first install git lfs and clone the repository by running `git lfs clone <url>`

Or you can download the file [here](https://github.com/NeLy-EPFL/NeuroMechFly/blob/main/data/design/blender/neuromechfly_full_model.blend) by simply clicking on download button.

**Comment by zhaojiachen1994** [comment]
It works. Thank you very much!

**Comment by gizemozd** [comment]
No problem!

**Comment by dneuhof** [comment]
Hello @gizemozd ,
I cannot fetch the blender file with `git clone lfs`:
```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/NeLy-EPFL/NeuroMechFly.git/info/lfs'
```
