### ISSUE TITLE
How to export blender model into sdf file

### ISSUE THREAD

**Issue by zhaojiachen1994** [NeLy-EPFL/NeuroMechFly#46]
Hello,

I found your code in Blender to obtain information about bones. but how to generate the SDF file based on the blender file? I didn't find code to implement this in this repository. Did you use some toolbox?

I am trying to build a simple animal SDF file (using a ball, box, or cylinder not mesh).

Thanks a lot for your help.

**Comment by gizemozd** [comment]
Hello,

Unfortunately, we do not provide support for the SDF generation from Blender as it is currently a part of another work in progress. 

Having said that, if you want to replace the mesh with simple geometric objects, you can have a look at this [code](https://github.com/NeLy-EPFL/NeuroMechFly/blob/main/scripts/model/change_sdf_forelegs.py) (Supp Figure 9 in the paper). Here, we change the antennae and forelegs with cylinders to test the effect of detailed morphology. 

Hope it helps!
